### ISSUE TITLE
Flameshot does not work with multiple monitors

### ISSUE THREAD

**Issue by brockn8r** [flameshot-org/flameshot#1184]
**Flameshot version**
Flameshot v0.8.5
Compiled with Qt 5.14.2

**Describe the bug**
When I invoke flameshot, whether via DM or the commandline, it only allows me to screen cap from my primary monitor. If I open the launcher and move to the other monitor, same thing (i.e., the prompting for a region to select goes over to the primary monitor).

**To Reproduce**
Really? Launch flameshot on a multiple monitor workstation, running with Fedora 32/Wayland, and take in the sadness caused by your soon-to-be ex-favorite-tool, flameshot.

**Expected behavior**
I would expect to screen cap across all active monitors/visible workspaces.

**System Information**
Fedora 32, and Wayland. Any other information?

**Comment by alxckn** [comment]
I'm able to span multiple screens by launching flameshot with xwayland (running fedora 32 wayland as well):

```bash
QT_QPA_PLATFORM=xcb flameshot
```

https://github.com/flameshot-org/flameshot/issues/668#issuecomment-639928999

**Comment by brockn8r** [comment]
Thank-you alxckn. Your reply indirectly provided me with a work-around. I tried multiple things:

```
1. QT_QPA_PLATFORM=xcb flameshot gui
2. QT_QPA_PLATFORM=wayland flameshot gui
3. QT_QPA_PLATFORM=xwayland flameshot gui
4. export QT_QPA_PLATFORM=xcb flameshot gui
5. export QT_QPA_PLATFORM=wayland flameshot gui
6. export QT_QPA_PLATFORM=xwayland flameshot gui
```

None of that worked. Then I saw that someone with an older version of fedora recommended installing qt5-qtwayland. So I did that and rattempted all of the above again. Still no joy! 

In a last ditch effort, I added "export QT_QPA_PLATFORM=xcb" to my bashrc file and rebooted. Now it works. flameshot spans both monitors. Thanks again. Hopefully, this helps someone else.

**Comment by alxckn** [comment]
Glad that helped. However I believe setting QT_QPA_PLATFORM in your .bashrc might affect other qt apps.

Just in case that was part of your issue, before launching flameshot with X you need to make sure that it's not already running in the background (ie `ps -aux | grep flameshot` and kill that pid if you find it).
If you are aiming at having flameshot as a startup program or simply be able to use the gnome launcher, you need to update the .desktop config file (/usr/share/applications/org.flameshot.Flameshot.desktop) exec command: `Exec=env QT_QPA_PLATFORM=xcb flameshot`.

**Comment by brockn8r** [comment]
I am assuming you're correct in that would impact all qt apps; so, I went ahead and modified the .desktop config file in hopes of wrapping this up. Unfortunately, that did not work either. After many attempts (modifying each Exec line, 1 at a time), I finally gave up. I also made sure that before each attempt, I killed the lingering flameshot process from the previous attempt.

The only way to get flameshot to span multiple monitors on my machine is to make sure the env var, QT_QPA_PLATFORM, is set to xcb at boot/login. I can't even get it to take (span multiple monitors) from the command line (i.e., running "QT_QPA_PLATFORM=xcb flameshot gui")

**Comment by edwinortizp123** [comment]
I have the same problem using flameshot on windows. Only works in one of my screens.

My version is 0.84

**Comment by borgmanJeremy** [comment]
@edwinortizp123 Can you please open a separate issue for your issue on Windows?

**Comment by borgmanJeremy** [comment]
Solved with PR #1282

**Comment by Anon-Exploiter** [comment]
JFYI the issue still resides on windows

**Comment by mmahmoudian** [comment]
@Anon-Exploiter this issue is about Linux and particularly Wayland. If you have the latest version of Flameahot and have this issue on windows, please first make sure this is not reported before (search in open and closed issues), and if it is not, please open a new issue.

**Comment by Lungshot** [comment]
Same issue here - on windows. I read the above. If he created a windows issue please link, I can't find it.

**Comment by alba4k** [comment]
Still happening on hyprland btw

forcing xwayland kinda works, except flameshot never gets focus (so I can not use any keyboard-driven functions in it)

**Comment by VaiOnko** [comment]
Still happening on KDE Wayland too.

**Comment by StayPirate** [comment]
Still happening on Sway v1.8.1 and Flameshot v12.1.0.

The [workaround suggested](https://github.com/flameshot-org/flameshot/issues/1184#issuecomment-744761384) by @alxckn works for me.

**Comment by overtomanu** [comment]
I also faced this issue on KDE plasma on Fedora 38.
The [workaround suggested](https://github.com/flameshot-org/flameshot/issues/1184#issuecomment-744761384) by @alxckn works for me.

**Comment by tyler36** [comment]
@Lungshot 
Same issue. Flameshot `1.12.1` only showed on primary monitor 1.

I un-installed, restarted, installed (`winget add flameshot`). Now shows on both monitors.

**Comment by richbai90** [comment]
This remains an issue on KDE plasma running Arch Linux

**Comment by Potato22** [comment]
on KDE Wayland, there is a workaround using Kwin rules.

add:
- Position (apply initially): 0 x 0
- Fullscreen: no

![2023-12-03_17-15](https://github.com/flameshot-org/flameshot/assets/39096741/303c1bd3-45be-40dc-b6b1-2531107c7931)

**Comment by Potato22** [comment]
a little bit of an update, this workaround no longer works on KDE6. I have not yet found a workaround for this version yet unfortunately.

**Comment by EliederSousa** [comment]
It's still an issue in Debian 12, KDE Plasma 5.27.5 (Wayland)

**Comment by igruntplay** [comment]
hmmm Windows 10 still happening, any fix to this?

**Comment by thibaut-cens** [comment]
BTW if you're using hyprland (which is not officialy supported by flameshot) you can use a combination of the following tricks :

Edit `$HOME/.config/hypr/hyprland.conf` with the following lines : 

```
windowrulev2=move 0 0,class:(flameshot),title:(flameshot)
windowrulev2=pin,class:(flameshot),title:(flameshot)
windowrulev2=fakefullscreen,class:(flameshot),title:(flameshot)
windowrulev2=float,class:(flameshot),title:(flameshot)
```

and run flameshot like so : 
``` bash
XDG_CURRENT_DESKTOP=sway flameshot gui
```

**Comment by bryndin** [comment]
Still a problem with v12.1.0 on Windows.    This is a big dealbreaker for adoption.

**Comment by igruntplay** [comment]
> Still a problem with v12.1.0 on Windows. This is a big dealbreaker for adoption.

i found some kind of solution:
1. Uninstall the program
2. Connect the 2nd monitor/screen
3. Install the program

**Comment by bryndin** [comment]
> Still a problem with v12.1.0 on Windows. This is a big dealbreaker for adoption.

The workaround is to restart Flameshot after the new screen is plugged in.

**Comment by Rush-er** [comment]
> on KDE Wayland, there is a workaround using Kwin rules.
> 
> add:
> 
> * Position (apply initially): 0 x 0
> * Fullscreen: no
> 
> UPDATE: on newer KDE6, you might want to reapply the rule by deleting the existing rule and making a new one by right-clicking the Flameshot configuration window and adding "Application rule".
> 
> Regardless, it's still a little bit funky and remains unsolved. ![2023-12-03_17-15](https://private-user-images.githubusercontent.com/39096741/287510626-303c1bd3-45be-40dc-b6b1-2531107c7931.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyODIwNzQsIm5iZiI6MTcxODI4MTc3NCwicGF0aCI6Ii8zOTA5Njc0MS8yODc1MTA2MjYtMzAzYzFiZDMtNDViZS00MGRjLWI2YjEtMjUzMTEwN2M3OTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDEyMjkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmYmJjYTdjY2Y2OGE3NDVmODE3MDc0M2Q4YjRjMjAzNGVlZTFhZjVlNGVmZjQxMGE1NTZmMGViYjAyMzJiYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8QHdlZryFeH8GYoCvv1jxD1a_4cd2WaPrMOaA51JePs)

This workaround is working on Fedora 40 with KDE Plasma 6.0.5

**Comment by bogdevil13** [comment]
> > Still a problem with v12.1.0 on Windows. This is a big dealbreaker for adoption.
> 
> The workaround is to restart Flameshot after the new screen is plugged in.

This really fixed the issue for me in MacOS. 
Thanks

**Comment by Megalomaniak** [comment]
You are lucky it at least lets you screenshot your primary monitor...

**Comment by AhmadEltobshy** [comment]
for windows 11 it still persist but i have figured the issue, when the second mentor has a little shift
like this 
![image](https://github.com/user-attachments/assets/03d10c40-2ef9-4f6e-af6e-d492e2ffdfd6)


the tool is take the whole rectangular of the both of monitors, making blank areas in the two monitors i highlight with red lines like this
![image](https://github.com/user-attachments/assets/f2528943-2126-46c5-bbc7-a85ca8b7bd8b)

and try to map this full rectangle to the (0,0) of the main monitor, which creates a messy black area in the to monitors

==========================================
my workaround (if the two monitors have the same resolution and the position wouldn't be matter for now)
to align the two monitors to be either horizontally like this
![image](https://github.com/user-attachments/assets/047b296c-f7de-4df9-adf7-c63d2e41c501)

or vertically [i assume it will work according to the above assumptions but i didn't test]

 it works for me!

**Comment by tonyd33** [comment]
Just in case someone else is stumbling upon this thread while trying to fix this on Hyprland like I did, the following rules fixed it for me:
```
# noanim isn't necessary but animations with these rules might not look good. use at your own discretion.
windowrulev2 = noanim, class:^(flameshot)$
windowrulev2 = float, class:^(flameshot)$
windowrulev2 = move 0 0, class:^(flameshot)$
windowrulev2 = pin, class:^(flameshot)$
```

**Comment by Potato22** [comment]
I'm surprised that this still hasn't been looked upon let alone fixed for the last 4 years.. People are still actively encountering this issue evidenced by the sustained activity of this issue.

**Comment by rochacbruno** [comment]
> on KDE Wayland, there is a workaround using Kwin rules.
> 
> add:
> 
>     * Position (apply initially): 0 x 0
> 
>     * Fullscreen: no
> 
> 
> UPDATE: on newer KDE6, you might want to reapply the rule by deleting the existing rule and making a new one by right-clicking the Flameshot configuration window and adding "Application rule".
> 
> Regardless, it's still a little bit funky and remains unsolved. ![2023-12-03_17-15](https://private-user-images.githubusercontent.com/39096741/287510626-303c1bd3-45be-40dc-b6b1-2531107c7931.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2ODczMjIsIm5iZiI6MTcyNzY4NzAyMiwicGF0aCI6Ii8zOTA5Njc0MS8yODc1MTA2MjYtMzAzYzFiZDMtNDViZS00MGRjLWI2YjEtMjUzMTEwN2M3OTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDA5MDM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NDM1YmMyM2UyYWYzYTBhZTVhNTQ3MWI3MzQ3MjZhZmVjZWQ0MTQ1ODZjZmRkZTRlYjQ1MjdlMTdjMDFhN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PjJ00Id2rRumkx_AUFIvKcrcjmnjpVUNanft5RUjEPs)

I confirm this fixed the issue on KDE Plasma 6.1 - Arch Linux, the only note is that `flameshot` class need to be all lower case.

**Comment by leonik375** [comment]
Same issue on Plasma 6.1.5/Gentoo
Fixed with 


    on KDE Wayland, there is a workaround using Kwin rules.

    add:

    * Position (apply initially): 0 x 0

    * Fullscreen: no

**Comment by Developer-dreamer** [comment]
> Thank-you alxckn. Your reply indirectly provided me with a work-around. I tried multiple things:
> 
> ```
> 1. QT_QPA_PLATFORM=xcb flameshot gui
> 2. QT_QPA_PLATFORM=wayland flameshot gui
> 3. QT_QPA_PLATFORM=xwayland flameshot gui
> 4. export QT_QPA_PLATFORM=xcb flameshot gui
> 5. export QT_QPA_PLATFORM=wayland flameshot gui
> 6. export QT_QPA_PLATFORM=xwayland flameshot gui
> ```
> 
> None of that worked. Then I saw that someone with an older version of fedora recommended installing qt5-qtwayland. So I did that and attempted all of the above again. Still no joy!
> 
> In a last ditch effort, I added "export QT_QPA_PLATFORM=xcb" to my bashrc file and rebooted. Now it works. flameshot spans both monitors. Thanks again. Hopefully, this helps someone else.

IT FINALLY WORKS, THX!

**Comment by Hasan-Rifat** [comment]
> on KDE Wayland, there is a workaround using Kwin rules.
> 
> add:
> 
> * Position (apply initially): 0 x 0
> * Fullscreen: no
> 
> UPDATE: on newer KDE6, you might want to reapply the rule by deleting the existing rule and making a new one by right-clicking the Flameshot configuration window and adding "Application rule".
> 
> Regardless, it's still a little bit funky and remains unsolved. ![2023-12-03_17-15](https://private-user-images.githubusercontent.com/39096741/287510626-303c1bd3-45be-40dc-b6b1-2531107c7931.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNDM2ODUsIm5iZiI6MTczNTE0MzM4NSwicGF0aCI6Ii8zOTA5Njc0MS8yODc1MTA2MjYtMzAzYzFiZDMtNDViZS00MGRjLWI2YjEtMjUzMTEwN2M3OTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDE2MTYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwM2M1ZjhmNjc5YWEyZTk2OTQ3Y2RiMDgyNDcyMDU4OGNkZjk1NzBhZjMyODlhNWIwYWU0Zjg3YzE5MjgzN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LLFDRTdqJEeD-kHZqhWg7sgRDSY9uSTxtHJAMtEd_IY)

its working for fedora kde thank you

**Comment by gleitoncampos** [comment]
> on KDE Wayland, there is a workaround using Kwin rules.
> 
> add:
> 
>     * Position (apply initially): 0 x 0
> 
>     * Fullscreen: no
> 
> 
> UPDATE: on newer KDE6, you might want to reapply the rule by deleting the existing rule and making a new one by right-clicking the Flameshot configuration window and adding "Application rule".
> 
> Regardless, it's still a little bit funky and remains unsolved. ![2023-12-03_17-15](https://private-user-images.githubusercontent.com/39096741/287510626-303c1bd3-45be-40dc-b6b1-2531107c7931.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3MDA3NjYsIm5iZiI6MTczNTcwMDQ2NiwicGF0aCI6Ii8zOTA5Njc0MS8yODc1MTA2MjYtMzAzYzFiZDMtNDViZS00MGRjLWI2YjEtMjUzMTEwN2M3OTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAxVDAzMDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MDliYzcyOWM5YzE0OGVkYjRhMzhmYzViMzNhOWM1M2M0NGQ1NzA2YTUxYjVhOWQyMTU5ZjhjMWFkZmViMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oFlKxvMvUjg_VBwMqTLS6uxd3R91nbxtpZI-uoS3lps)

+1 In Fedora KDE 41 and this workaround always works form me. And not a single word of devs about this near 5 year bug..

**Comment by SkyH34D** [comment]
> [@Lungshot](https://github.com/Lungshot) Uninstall and reinstall. Had the same issue and was fixed with that.

Had the same issue. Reinstalling didn't work but disconnecting and connecting the screen cable did.

**Comment by BarakXYZ** [comment]
For me I needed to negate the offset of my screen to not push other windows around:

```conf
# Negate the offset of your screen. Set to 0 0 if there's no offset.
windowrulev2=move -1080 -320,class:(flameshot),title:(flameshot)
# shows the window on all workspaces
windowrulev2=pin,class:(flameshot),title:(flameshot)
# tell the application it's in fullscreen mode
windowrulev2=fullscreenstate,class:(flameshot),title:(flameshot)
# force the window to be floating ( not in a tiled pane )
windowrulev2=float,class:(flameshot),title:(flameshot)
bindl=,Print,exec, hyprctl dispatch exec flameshot gui # Screenshot >> clipboard
```

Also setting the protocol to `useGrimAdapter=true` made issues on my setup. Not sure why. Had to remove this from the flameshot.ini conifg to get things working properly.

Thanks to ryan for initial clues that got me thinking in that direction:
https://www.ryanwise.me/blog/flameshot-on-hyprland/

**Comment by n0body-special** [comment]
Same problem with Kubuntu 25.04 Plasma 6.3.4. It was solved by launching it with: `QT_QPA_PLATFORM=xcb flameshot` Thanks [alxckn](https://github.com/alxckn), I was ready to ditch this crap.

I'll never understand developers. You have this wonderful piece of software that's probably half you life and also happens to be ages ahead of everything else. One day something called Wayland comes up and breaks it, which is becoming the standard in desktop distros. The whole world sees the problem, but not the developers? What are they waiting for? Dunno, I'll never understand.

**Comment by richbai90** [comment]
It's not that they don't see it, it's that software is complex and it's
usually a team of one developing and maintaining it for free in their spare
time. A lot of non enterprise apps need workarounds for Wayland because
it's a completely different system with a different API and different
security requirements. I understand it can be frustrating, but you can't
complain if you are unwilling to or unable to help.

**Comment by spagnoloG** [comment]
I added the environment variable as @alxckn suggested, and now it works on a multimonitor setup. However, a new issue appeared: keyboard shortcuts no longer work, only mouse commands do. The following error is shown:
`Flameshot has lost focus. Keyboard shortcuts won't work until you click anywhere`
(but they still don’t work even after clicking anywhere).

```bash
    bindsym Print exec sh -c 'QT_QPA_PLATFORM=xcb QT_AUTO_SCREEN_SCALE_FACTOR=1 flameshot gui'
```

has anyone had any similar issues on wayland / swaywm?

**Comment by aktashakan** [comment]
> for windows 11 it still persist but i have figured the issue, when the second mentor has a little shift like this ![image](https://github.com/user-attachments/assets/03d10c40-2ef9-4f6e-af6e-d492e2ffdfd6)
> 
> the tool is take the whole rectangular of the both of monitors, making blank areas in the two monitors i highlight with red lines like this ![image](https://github.com/user-attachments/assets/f2528943-2126-46c5-bbc7-a85ca8b7bd8b)
> 
> and try to map this full rectangle to the (0,0) of the main monitor, which creates a messy black area in the two monitors
> 
> ==========================================
> 
> ### Work around
> my workaround (if the two monitors have the same resolution and the position wouldn't be matter for now) to align the two monitors to be either horizontally like this ![image](https://github.com/user-attachments/assets/047b296c-f7de-4df9-adf7-c63d2e41c501)
> 
> or vertically [i assume it will work according to the above assumptions but i didn't test]
> 
> it works for me!

it works for me. thanks a lot.

**Comment by jzr-supove** [comment]
On Fedora, I've created .sh script that executes this command:

```bash
QT_QPA_PLATFORM=xcb flameshot gui -r | wl-copy
```

and bound it to the custom hotkey F8.

Working like a charm!
