### ISSUE TITLE
Flameshot displays wrong tray icon

### ISSUE THREAD

**Issue by kpcee** [flameshot-org/flameshot#1378]
When the welcome message is turned on, Flameshot shows a wrong tray icon. As soon as it is turned off, it works as it should.

![Unbenannt](https://user-images.githubusercontent.com/39984895/108620588-5d252d80-742d-11eb-86d9-b46180bfc756.png)

Arch Linux, Xfce
Git version (commit 5b0bb501dc513f16e93a6d72e06a222a2da6c404)

**Comment by ZetaoYang** [comment]
@kpcee Can you show us your git config, especially `core.symlinks`? `git config --system --list`

**Comment by ZetaoYang** [comment]
@kpcee The reason may be these two files are symlinks,
```
 data/img/app/flameshot.png
 data/img/app/flameshot.svg
```

**Comment by kpcee** [comment]
Yes, the symlinks are also available here, link to the correct icon file. But the correct icon is not displayed in the tray. I have also just cloned the repository completely new and compiled, but changes nothing in the display.

**Comment by borgmanJeremy** [comment]
This looks like XFCE? I dont have any icons for the welcome bubble on KDE, but I'll test on the same DE as you.

**Comment by kpcee** [comment]
Yes I use Xfce with Arch Linux.

**Comment by borgmanJeremy** [comment]
I think this is a qt or xfce issue. It works properly on KDE.

After investigating it I believe our code is correct: https://github.com/flameshot-org/flameshot/blob/39dcd1a2918ee2dfc7a692a3b3040f88fe0c852c/src/core/controller.cpp#L504

That is where the information bubble is created. We set a timeout for 3seconds with an "info" icon. When this expires the icon should switch back.

**Comment by borgmanJeremy** [comment]
Even though this is clearly not a flameshot bug perhaps we should rework the code to use the flameshot icon instead of the info icon just to clear confusion.

**Comment by fdmarcin** [comment]
Also happens on Manjaro + XFCE

Flameshot 0.9.0
XFCE 4.16

**Comment by arcolinuxz** [comment]
I can confirm the icon is unchangeable by the icon theme. 

It will choose the dialog-information.svg or png - seeing the code up here 'QSystemTrayIcon::Information, '
that makes sense to me.

Please revert back so that icon developers can keep using flameshot-tray.svg or png or ....
make it possible to select whatever icon in the app.

**Comment by borgmanJeremy** [comment]
This issue is still open, planning to change it before the 0.9.1 patch release. Again this is really an upstream bug, but we can tweak our code to mask the issue.

**Comment by borgmanJeremy** [comment]
fixed with #1474

**Comment by fre-ac** [comment]
Slackware 15 Xfce 4.16 , Flamesnot v.0.10.1 - 
![flameshot_icon_xfce416](https://user-images.githubusercontent.com/85880630/132118659-fa5234c2-e067-420e-b4ee-1a5e2cf22f53.png)
the flameshot tray icon is still incorrect

**Comment by mmahmoudian** [comment]
@fre-ac how have you installed Flameshot?

**Comment by fre-ac** [comment]
Compilation from source. But running as root, it shows the correct icon. 
![flameshot_as_root](https://user-images.githubusercontent.com/85880630/132138888-c74361c4-7040-45b6-bfc4-8d8999472ed7.png)

**Comment by fre-ac** [comment]
I also ran the Flameshot-0.10.1.x86_64.AppImage file, but it doesn't save the screenshot (the window disappears quickly). Shows only the English language, not my locale.

**Comment by mmahmoudian** [comment]
@fre-ac what if you turn off the welcome message? In [the first post of this thread](https://github.com/flameshot-org/flameshot/issues/1378) it is mentioned that this only happens when the welcome message is on and it would work as expected if you turn it off.

**Comment by fre-ac** [comment]
Yes, I know that disabling the welcome message will display the correct icon. It works for me.

**Comment by fre-ac** [comment]
Appimage also doesn't show the icon

**Comment by mmahmoudian** [comment]
Ok, considering that it is the same issue on the same DE but just a different distro, I think we should reopen this issue.

@borgmanJeremy do you have any quick guess about this?

**Comment by fre-ac** [comment]
Is there an idea to fix the problem?

**Comment by fre-ac** [comment]
I compiled the Github version on September 17th, and I have to say that now the tray icon is displayed correctly :)
![xfce_416_flameshot_tray_icon](https://user-images.githubusercontent.com/85880630/133779581-c78e5a92-e9b2-4c0e-b1a1-f9cf2e2316f7.png)

**Comment by fre-ac** [comment]
I was happy too soon, the icon is wrong again. This happened after changing the appearance of the desktop. It is impossible to change the icon back 
![2021-09-22_22-33](https://user-images.githubusercontent.com/85880630/134419368-31cac4a0-6e1e-4383-b730-26718c8858cd.png)
:(

**Comment by fre-ac** [comment]
After a few rebots, the icon is correct again
![2021-09-22_22-58](https://user-images.githubusercontent.com/85880630/134421000-b57bd108-293e-4d12-ac90-07a84fea8a08.png)

**Comment by borgmanJeremy** [comment]
Hmmm this is very strange

**Comment by fre-ac** [comment]
I will pay attention to it, I will let you know

**Comment by borgmanJeremy** [comment]
I don't know much about slackware. Is it possible you have multiple versions of Flameshot installed and one of them is the old version with the bug?

I grepped the code base and we are not referencing that "information" icon anymore.

**Comment by mmahmoudian** [comment]
Is it also possible that Xfce use that information icon as placeholder when it has some issues displaying the correct one? 🤔

**Comment by fre-ac** [comment]
You were probably right with the old version, I have reinstalled the Flameshot package, everything is fine now, the tray icon works. Thank you.

**Comment by fre-ac** [comment]
The package was compiled from the source code from Github on September 17th
