### ISSUE TITLE
截图光标位置几乎找不到，功能按钮希望能添加鼠标悬浮提示信息

### ISSUE THREAD

**Issue by Jial08** [flameshot-org/flameshot#1797]
系统：
Manjaro21.1.0
描述：
在开始截图后截图光标几乎找不到，因为不能截图后再截图，用手机拍照，效果不好，在纯黑背景下，光标还稍微能看到
![7c37ddca91a7848f7fa04a8bd3e9b86](https://user-images.githubusercontent.com/25861104/127882940-3c65e56b-a22c-4677-99d9-f1dfaea6c535.jpg)
在白色背景下，光标找不到位置
![de6dfb0b77040ea46aab12d009fe12c](https://user-images.githubusercontent.com/25861104/127883071-bd00eef3-e92f-47e8-a6af-3e78ce13b47c.jpg)
感觉 Snipaste 做的就很好，光标位置清晰可见，望作者借鉴
![截图_2021-08-02_23-08-57](https://user-images.githubusercontent.com/25861104/127883517-3d8996d0-3c23-4625-a1dd-0dab9feaacb3.png)
另外希望能像 Snipaste 那样有功能按钮鼠标悬浮提示，如下
![截图_2021-08-02_22-57-54](https://user-images.githubusercontent.com/25861104/127883168-b4ed98ba-d3e6-4fe0-bfb4-433b052e385c.png)
感谢大大的付出

**Comment by mmahmoudian** [comment]
Translations from Google Translate:

**Title**:
The cursor position of the screenshot can hardly be found, and the function button hopes to add a mouse hovering prompt message


**Body**

system:
 Manjaro21.1.0
 Flameshot:
 v0.10.1

 describe:
 After starting to take a screenshot, the cursor can hardly be found, because you can’t take a screenshot and then take a screenshot. The effect is not good. The cursor can still be seen slightly under a pure black background.

[First Image]

On a white background, the cursor cannot find the position

[Second Image]

I feel that Snipaste is doing very well, and the cursor position is clearly visible. I hope the author can learn from it

[Third Image]

In addition, I hope to have a function button mouse hover prompt like Snipaste, as follows

[Fourth Image]

Thanks for the great contribution

**Comment by mmahmoudian** [comment]
First point is duplicate of #863

Second point is a feature request, but I really don't understand what should be improved.

**Comment by hosiet** [comment]
For the second feature request, I believe we have already implemented it long ago:

![图片](https://user-images.githubusercontent.com/8443926/127926061-2bb35fe9-b0fe-4aa5-ad2d-99488f57219a.png)

@Jial08 Is it what you are proposing?

**Comment by Jial08** [comment]
> For the second feature request, I believe we have already implemented it long ago:
> 
> ![图片](https://user-images.githubusercontent.com/8443926/127926061-2bb35fe9-b0fe-4aa5-ad2d-99488f57219a.png)
> 
> @Jial08 Is it what you are proposing?

您好,我用 pacman -S flameshot 安装的确实没有鼠标悬浮提示,但是 Flameshot-0.10.1.x86_64.AppImage 却可以,应该是包的问题吧,感谢

**Comment by mmahmoudian** [comment]
Translation from Google Translate

> Hello, I used pacman -S flameshot to install and there is no mouse hovering prompt, but Flameshot-0.10.1.x86_64.AppImage is OK, it should be a problem with the package, thanks

**Comment by mmahmoudian** [comment]
@Jial08 what is the version of your Flameshot that you installed with pacman and still does not have the tooltip?

**Comment by Jial08** [comment]
> @Jial08 what is the version of your Flameshot that you installed with pacman and still does not have the tooltip?

![image](https://user-images.githubusercontent.com/25861104/127966060-acf5b4b8-7e16-453c-850b-4adc72a0f67b.png)

**Comment by mmahmoudian** [comment]
@Jial08 I removed flameshot and installed it again with pacman and I cannot reproduce this behavior:

![image](https://user-images.githubusercontent.com/390889/127975465-44bf085b-c7da-4830-a030-39eaecc4800d.png)


What is your DE (Desktop Environment)?
Please provide us the output of the following command:

```sh
inxi --system --graphics --width 80
```

**Comment by Jial08** [comment]
> @Jial08 I removed flameshot and installed it again with pacman and I cannot reproduce this behavior:
> 
> ![image](https://user-images.githubusercontent.com/390889/127975465-44bf085b-c7da-4830-a030-39eaecc4800d.png)
> 
> What is your DE (Desktop Environment)?
> Please provide us the output of the following command:
> 
> ```shell
> inxi --system --graphics --width 80
> ```

System:
  Host: jl-qtk5 Kernel: 5.10.53-1-MANJARO x86_64 bits: 64 Desktop: Xfce 4.16.0 
  Distro: Manjaro Linux 
Graphics:
  Device-1: Intel 4th Gen Core Processor Integrated Graphics driver: i915 
  v: kernel 
  Device-2: NVIDIA GM107M [GeForce GTX 860M] driver: nvidia v: 470.57.02 
  Device-3: Chicony USB HD Webcam type: USB driver: uvcvideo 
  Display: x11 server: X.Org 1.20.11 driver: loaded: modesetting,nvidia 
  unloaded: intel,nouveau resolution: 1: 1920x1080~60Hz 2: 1920x1080~60Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics 4600 (HSW GT2) 
  v: 4.5 Mesa 21.1.5

**Comment by mmahmoudian** [comment]
Translation using Google Translate

> Hello, my software is in Chinese, may it be related to my use of domestic sources?

**Comment by mmahmoudian** [comment]
@Jial08 Do you use "Chinese (Simplified)" or "Chinese (Traditional)"?

**Comment by Jial08** [comment]
> Chinese (Simplified)

Chinese (Simplified)

**Comment by mmahmoudian** [comment]
Then I'm out of ideas. I had a hunch that because Chinese Traditional is not fully translated, some of the tooltips might not show up, but now I don't know what is wrong. 🤔

**Comment by Jial08** [comment]
> Then I'm out of ideas. I had a hunch that because Chinese Traditional is not fully translated, some of the tooltips might not show up, but now I don't know what is wrong.

Thanks
