### ISSUE TITLE
Launching takes very long time

### ISSUE THREAD

**Issue by Histmy** [flameshot-org/flameshot#2268]
### Flameshot Version

Flameshot v11.0.0 ()
Compiled with Qt 5.12.8

### Installation Type

AppImage, Using the ready-made package from Github Releases, Compiled from source

### Operating System type and version

Linux Mint 20.3 Cinnamon

### Description

First I have tried installing Flameshot from deb package from GitHub release. When I ran command `flameshot gui`, it would say: `qt5ct: using qt5ct plugin` and then wait for around 25 seconds and then it would finally show the GUI. Before upgrading to v11 I was using version maybe 0.8 or 0.6 I don't remember exactly. And at first I had the same issue, but then I got it fixed somehow and I forgot how, but I think I installed it from somewhere else but I am not sure. After that I tried to compile it myself, but It was behaving the same. As a last resort I tried appimage and that is kind of working. When launching it from terminal it displays `Failed to get information about the latest version.  "Host api.github.com not found"` but the GUI will show after about half a second. Even tho the appimage relatively works I would prefer to use the package because when it did work it was a little bit faster and it is much more pleasant to use.

### System Information

System:
  Host: HistmyPC Kernel: 5.4.0-94-generic x86_64 bits: 64 
  Desktop: Cinnamon 5.2.7 Distro: Linux Mint 20.3 Una 
Graphics:
  Device-1: NVIDIA GP107 [GeForce GTX 1050 Ti] driver: nvidia v: 470.86 
  Display: x11 server: X.Org 1.20.13 driver: nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa resolution: 1440x900~60Hz 
  OpenGL: renderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 
  v: 4.6.0 NVIDIA 470.86
Monitors: 2
 0: +*DP-0 1920/544x1080/303+0+0  DP-0
 1: +DVI-D-0 1440/408x900/255+1920+153  DVI-D-0
![layout](https://user-images.githubusercontent.com/59661489/149669690-b9c5ae22-73ed-4276-be93-9f3ab907845a.png)

**Comment by borgmanJeremy** [comment]
After thinking a bit my gut says the version of qt your system provides has a bug that results in poor performance. When you use the appimage you are using a newer version of qt with the bug fixed.


That's my best guess.

**Comment by borgmanJeremy** [comment]
Actually could you also post your config file? I wonder if turning off update checking will fix it.

**Comment by Histmy** [comment]
What config file do you mean?

**Comment by borgmanJeremy** [comment]
It's located in ~/.config/flameshot/flameshot.ini

Also go into the config menu and disable update checking.

**Comment by Histmy** [comment]
```ini
[General]
contrastOpacity=188
copyAndCloseAfterUpload=true
disabledTrayIcon=true
drawColor=#ff0000
drawThickness=3
savePath=/home/histmy/Desktop
savePathFixed=false
showDesktopNotification=false
showHelp=false
showSidePanelButton=false
showStartupLaunchMessage=false
startupLaunch=true

[Shortcuts]
TYPE_ARROW=A
TYPE_CIRCLE=C
TYPE_CIRCLECOUNT=
TYPE_COMMIT_CURRENT_TOOL=Ctrl+Return
TYPE_COPY=Ctrl+C
TYPE_DELETE_CURRENT_TOOL=Del
TYPE_DRAWER=D
TYPE_EXIT=Ctrl+Q
TYPE_MARKER=M
TYPE_MOVESELECTION=Ctrl+M
TYPE_MOVE_DOWN=Down
TYPE_MOVE_LEFT=Left
TYPE_MOVE_RIGHT=Right
TYPE_MOVE_UP=Up
TYPE_OPEN_APP=Ctrl+O
TYPE_PENCIL=P
TYPE_PIN=
TYPE_PIXELATE=B
TYPE_RECTANGLE=R
TYPE_REDO=Ctrl+Shift+Z
TYPE_RESIZE_DOWN=Shift+Down
TYPE_RESIZE_LEFT=Shift+Left
TYPE_RESIZE_RIGHT=Shift+Right
TYPE_RESIZE_UP=Shift+Up
TYPE_SAVE=Ctrl+S
TYPE_SELECTION=S
TYPE_SELECTIONINDICATOR=
TYPE_SELECT_ALL=Ctrl+A
TYPE_TEXT=T
TYPE_TOGGLE_PANEL=Space
TYPE_UNDO=Ctrl+Z
```
This is my config.ini. And the update checking has no effect on performance in the build nor in the appimage.

**Comment by j-tai** [comment]
I am also experiencing this after upgrading to v11.0.0. It takes around 2 seconds to start a screenshot, *even when Flameshot is already running in the system tray*, compared to <0.5 seconds from v0.10.

I am using the Flatpak version (from Flathub), and using the PrtSc key which is bound to `flatpak run org.flameshot.Flameshot gui`.

Monitor setup:

![image](https://user-images.githubusercontent.com/45131430/149676531-ab4a0810-4a38-437e-b13a-ee71c465c8f4.png)
(1080p and 1440p)

**Comment by borgmanJeremy** [comment]
@j-tai what distro and DE?

**Comment by j-tai** [comment]
> @j-tai what distro and DE?

Pop!_OS 21.10, GNOME 40.

**Comment by borgmanJeremy** [comment]
Do you have nvidia graphics? I'm trying to find a commonality

**Comment by j-tai** [comment]
Yes I do, but it still seems to be slow (1 to 1.5 seconds) if I switch to integrated graphics (nvidia card is disabled).

**Comment by borgmanJeremy** [comment]
Does the speed change for either of you if you only use 1 monitor?

**Comment by borgmanJeremy** [comment]
i looked at this for an hour and cannot replicate it in multimonitor VM's.

**Comment by j-tai** [comment]
> Does the speed change for either of you if you only use 1 monitor?

The issue still occurs with 1 monitor.

**Comment by mmahmoudian** [comment]
@borgmanJeremy I have also experienced some lag in KDE Plasma Xorg, both for when starting Flameshot and for when I try to save on disk, but it behaves in a non-deterministic way, so I don't know in what circumstances it happens.It feels like process race for diskio, but when it happens it is too late to check the diskio. I'll keep a closer look at io to see if I can spot it.

**Comment by swartex** [comment]
I have the same problem with version 11.
rolled back to 0.10.2 and everything works fast

**Comment by borgmanJeremy** [comment]
@swartex what gpu and distro? By long time do you mean 1 second or 10seconds

**Comment by swartex** [comment]
> By long time do you mean 1 second or 10seconds
10 - 15 seconds 

> what gpu and distro?

GPU - Iris Graphics 540 (integrated graphics)

distro - Linux Mint 20

**Comment by borgmanJeremy** [comment]
Ok so that rules out Nvidia, it seems that there are two different issues here @mmahmoudian and @j-tai report a small performance regression (1-2 seconds) I do not want to discuss that on this thread anymore as I think its a seperate issue.

@swartex and @Histmy report a very long regression >10 seconds and are both on Mint + Cinnamon. I would like to keep this thread focused on that. 

I cannot replicate it in a VM, so it would be helpful if either of you could build from source and follow these directions to generate a flamegraph. It might point us in the right direction. https://github.com/flameshot-org/flameshot/issues/1901#issuecomment-921152555

**Comment by Histmy** [comment]
I thought I downloaded all needed dependences but when I tried to run the script I got error: `perf: command not found`. I tried to install it with `sudo apt install linux-tools-common` but now when running the script it seems to open `man` page for perf command. Do you know what I could have done wrong?

**Comment by glitchsys** [comment]
Interestingly I'm having the same exact problem. However, I have Linux Mint 20.3 on my older Dell Precision 5540 laptop and flameshot 11 loads instantly and works perfectly. But I have Linux Mint 20.3 on my newer Dell Precision 5560 laptop, and I have that several seconds delay before flameshot loads.  
If I load flameshot fully, so it sits in the system tray, it takes several seconds after loading it before it finally shows up in the system tray. But after that I can click on the icon in the systray and it instantly works. So it's just an initial loading delay.  If I hit "Print Screen" which I've configured to execute "/usr/bin/flameshot gui" , there's several seconds delay before it finally pops up for me to take a screenshot of a selected area. 

The only thing I can think of is that my older computer originally started out at Linux Mint 20.0, then upgraded to 20.1, then straight to 20.3;  so there could be remnant libraries or configs behind because I've used Flameshot on that installation for a lot longer. Maybe some older library followed me during the upgrade path and is what's keeping flameshot running better but on the new laptop w/ a clean Mint 20.3 install (which is Ubuntu 20.04.3 based) there's some mismatch. 

Happy to provide whatever debug files you need, libraries versions, etc.

**Comment by rodrigofbm** [comment]
receiving the same message: "Host api.github.com not found" and nothing happens

**Comment by yahyaanwar** [comment]
Same issue using Linux Mint 20 I installed a week ago.

```
yahya@linux-mint:~$ time /usr/bin/flameshot
qt5ct: using qt5ct plugin

real    0m25,716s
user    0m0,111s
sys     0m0,022s
```

**Comment by Gilnior** [comment]
I installed the last version with flatpak, and it was pretty slow, but installing it with snap solved my problem.

**Comment by mmahmoudian** [comment]
@yahyaanwar  which version and how did you install Flameshot?

**Comment by Gilnior** [comment]
Flameshot v11.0.0 ()
Compiled with Qt 5.12.8

Manjaro KDE

**Comment by yahyaanwar** [comment]
> @yahyaanwar which version and how did you install Flameshot?
> 
> @Gilnior what is your OS? Please provide your OS and DE details in addition to Flameshot versions

Sorry for my late reply. Here is my version.
```
Flameshot v11.0.0 ()
Compiled with Qt 5.12.8
```

Turns out, my Neovim had a delay too. After some browsing I came across this thread where a guy named dysfet had a solution that solved my problem. This is a temporary solution but it worked for me. I'm guest this problem from Qt side but I don't know much. 
https://forums.linuxmint.com/viewtopic.php?p=1982045#p1982045

**Comment by AtjonTV** [comment]
I too have a small performance issue with 2 second launch time from tray with keyboard shortcuts.

Here is my system:
```
Make: Tuxedo Computers
Model: Tuxedo Aura 15
Operating System: Arch Linux
KDE Plasma Version: 5.24.0
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.2
Kernel Version: 5.16.9-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Ryzen 7 4700U with Radeon Graphics
Memory: 30.7 GiB of RAM
Graphics Processor: AMD RENOIR
```
All packages are up-to-date.

Flameshot is installed from the community repository.

```
atjontv: atjontv $ flameshot --version
Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2
```

I have both Qt 5.15.2 and Qt 6.2.3 .

When starting from cli with `flameshot gui` it takes 0.8 seconds to show up.
When starting with keyboard shortcut it takes 2.3 seconds to show up.

System was install on last friday.

The homefolder was moved from old PC that had Gentoo Linux with Flameshot 0.8 to this one, Flameshot 11 told me that 3 settings where incompatible. In the prompt I removed them and later reconfigured them using the settings ui.

**Comment by ulexxander** [comment]
I am having the same issue.

Launching Flameshot by clicking on tray icon is fast, but trying to launch it via shortcut or CLI takes a very long time (~30sec).

```
OS: Linux Mint 20.3 x86_64
Kernel: 5.4.0-99-generic
Resolution: 2560x1440
DE: Cinnamon
WM: Mutter (Muffin)
CPU: AMD Ryzen 7 2700 (16) @ 3.014GHz
GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590
```

```
libqt5core5a:amd64                         5.12.8+dfsg-0ubuntu2.1
```

Tried both [flameshot-11.0.0-1.debian-10.amd64.deb](https://github.com/flameshot-org/flameshot/releases/download/v11.0.0/flameshot-11.0.0-1.debian-10.amd64.deb) and [flameshot-11.0.0-1.ubuntu-20.04.amd64.deb](https://github.com/flameshot-org/flameshot/releases/download/v11.0.0/flameshot-11.0.0-1.ubuntu-20.04.amd64.deb).

**Comment by Histmy** [comment]
So, today I noticed that my Qt library or whatever was causing the issue suddenly started to work? I don't know if some package updated or something, but everything which I had issue with is now working fine (Flameshot, Virtual box and QBittorrent).

My problem is solved so I think I should close this issue, but I will keep it open for a little while so somebody can respond if they have something to say.

**Comment by Histmy** [comment]
Because there are no new comments being posted here, I think it is safe to close this issue now. Everything still works for me, so it was probably an old dependency, that got randomly updated and not some bug in Flameshot so nothing to worry about that.

**Comment by mmahmoudian** [comment]
@Histmy these things are typically hard to track especially if we cannot reproduce it in a clean VM. let's hope that it doesn't happen again, but if it ever did, please consider reopenning this issue

**Comment by Gilnior** [comment]
I solved a problem related to version of python-qt, or something like that, for another software that I was having problem with, and the issue with flameshot was solved as well.

**Comment by mmahmoudian** [comment]
> I solved a problem related to version of python-qt, or something like that, for another software that I was having problem with, and the issue with flameshot was solved as well.

As far as I know, we do not use any python-qt in flameshot. Most probably you have updated something else along side of python-qt.

**Comment by glitchsys** [comment]
So I have to Linux Mint 20.3 laptops, near identical. I ran Flameshot 11.0.rc1-1 on one laptop and it loaded fast, the other laptop I had to purposely run Flameshot 0.10.2-1 because 11 loaded too slowly.  However, I just now decided to re-upgrade it to Flameshot 11.0.rc1-1 and this time it's loading and closing fast. I can't repro the issue I used to have. Maybe one of the myriad of library or kernel updates that have gotten installed between then and now have solved the issue. 

I also tried Flameshot 12, from flatpak, on both computers and Flameshot 12 loads fast.

**Comment by Pheggas** [comment]
>When starting from cli with flameshot gui it takes 0.8 seconds to show up.
When starting with keyboard shortcut it takes 2.3 seconds to show up.
@AtjonTV 

I had exactly the same issue. The custom shortcut file partially fixed it (although i had to change the command that executes as i have it installed from flatpak [so use `flatpak run org.flameshot.Flameshot gui`], and also needed to assign shortcut key in the GUI). However it still takes up to 0,5 seconds which is not instant like on my Windows machine that takes the screenshot immediately (not always but even if the GUI shows up later like already mentioned 0,5 seconds, it still shows screenshot taken back in the exact time i pressed the key).

Is there a way to make it even faster?

**Comment by mmahmoudian** [comment]
@Pheggas 
Yes you can make it a bit faster. Run the Flameshot daemon. For example using:

```sh
flatpak run org.flameshot.Flameshot
```

Then running `flatpak run org.flameshot.Flameshot gui` would be faster as everything is already loaded in RAM.

But I have a suggestion: please read a bit more about what is the difference between a native install and a Flatpal, Snap, and other similar containerized methods.

**Comment by sarunmrzn** [comment]
> @AtjonTV I guess the issue is with how KDE detects the DBus calls automatically. Please consider either using our KDE plasma keybindings file as explained [here in README](https://github.com/flameshot-org/flameshot#on-kde-plasma-desktop), or create a custom shortcut yourself and bind it to the `flameshot gui` command. Please let us know if the issue is resolved

I did this it did make it faster but its like 0.5 slow.

**Comment by linoskoczek** [comment]
Happened to me after update from Mint 20.1 to 20.3. 20 seconds delay between `qt5ct: using qt5ct plugin` output and actual start of Flameshot gui. 

Solution: Installed the version (also 12.1) from flatpak and it works fine.
