### ISSUE TITLE
Do not load translation when there is parameters

### ISSUE THREAD

**Issue by Hill-98** [flameshot-org/flameshot#2371]
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

ArchLinux

### Description

[main.cpp#L96](https://github.com/flameshot-org/flameshot/blob/master/src/main.cpp#L96)

Passing any arguments will result in no translation being loaded, which will result in only the default language being possible when using the `flameshot gui` command, and we should load the translation at all times.

Related issues: #651 #2368

### System Information

Operating System: Arch Linux
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.16.0-pf2 (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5700G with Radeon Graphics
Memory: 27.3 GiB of RAM
Graphics Processor: AMD RENOIR

**Comment by borgmanJeremy** [comment]
Can you test #2385

**Comment by Hill-98** [comment]
@borgmanJeremy It doesn't work, and it doesn't even load translations when there are no parameters.

I replaced the `install_translations()` call with the code for `install_translations`, which works with no arguments. I'm guessing it's a problem with the `qApp` in install_translations.

The second `install_translations()` call should not be on line 152, as the following code will delete the original `qApp`. 

We should probably consider refactoring `main()`

**Comment by borgmanJeremy** [comment]
Okay thanks for checking. I was rushing when I pushed that so I'll take a closer look at it this time. 

> We should probably consider refactoring main()
Haha this is an understatement

**Comment by fre-ac** [comment]
Hi, I also compiled the git version from February 20 and unfortunately only English is available. This happens during the command: **flameshot gui**. Another language will only be available when called from the tray icon.

**Comment by fre-ac** [comment]
My Operation System:
Slackware64 15,   Xfce 4.16,   QT 5.15.3

**Comment by fre-ac** [comment]
I'm trying to compile different git versions, but the translation bug is still unresolved. It's been 2 months since the bug was reported, but nothing has improved :(  A flameshot without shortcut keys is bound to disappoint

**Comment by borgmanJeremy** [comment]
What have you done to help resolve the bug? This is a community project, no one is paid. Consider trying to fix it yourself or post a bug bounty to get higher priority on an issue. I've been focusing on other bugs and new features.

**Comment by fre-ac** [comment]
When writing my post, I just wanted to emphasize that it is not easy to use software in a foreign language. I'm not going to force anyone to do anything.

**Comment by mmahmoudian** [comment]
@fre-ac I highly suggest that you use Rysolv. Similar to what I did, you can put a bounty on this issue and:
1. Create more incentive to get it solved
2. Attract attention to the issues you think are important

https://rysolv.com/issues/search/Flameshot
