### ISSUE TITLE
Flameshot gui not starting in Arch Linux

### ISSUE THREAD

**Issue by federicogibertoni** [flameshot-org/flameshot#2481]
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Arch Linux

### Description

When running ```flameshot gui``` from terminal after a fresh install from pacman I get this error:

"Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway."

Then nothing happens but flameshot keeps running in the background (visible from ```top```), no tray icon.

### Steps to reproduce

1. run ```flameshot gui``` from terminal

### System Information

Distro: Arch Linux x86_64
DE: GNOME 41.4 Wayland
Kernel: 5.16.13-arch1-1

**Comment by zacharytyhacz** [comment]
I am also on Arch Linux ( btw ) and experiencing `flameshot gui` not working.

System Information
Distro: Arch Linux x86_64
DE: i3 WM + Xorg server / X11
Kernel: 5.16.13-arch1-1

I get this error from i3 ( i use i3 binding to call `flameshot gui`, same error occurs in and outside of i3 )

```
Error: saveAfterCopyPath
```

```sh
> flameshot --version
Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2
```

I cloned the repo and did a search for this term `saveAfterCopyPath` and nothing comes up.

Therefore, I am assuming it could be clipboard related ( maybe `flameshot` needs a variable of which clipboard binary to use? ) 

```sh
local/xclip 0.13-3
    Command line interface to the X11 clipboard
local/xorg-xclipboard 1.1.3-3
    X clipboard manager

```

**Comment by federicogibertoni** [comment]
It's a completely different problem than the one described above.
I think you should open a new issue and not using this one.

**Comment by mmahmoudian** [comment]
@zacharytyhacz To me it seems you haven't updated Flameshot for a very long time which is very odd for a person on a rolling release distro! I think the issue is that you have a bad config file. Go to your `~/.config/flameshot/flameshot.ini` and remove the lines that contains `saveAfterCopyPath`. if the issue persisted, please open a new issue as your issue is irrelevant to this issue (which seems to be a Wayland issue)

**Comment by renaldofreire** [comment]
I have the same problem in my system

**Comment by federicogibertoni** [comment]
@renaldofreire Still no solution found, i'm waiting for an update or something.

**Comment by kpcee** [comment]
This is certainly not a problem that can be fixed by the flameshot developers. It affects Qt, since QSystemTrayIcon is used for the tray icon. Either it is Wayland ↔ Qt or it is a Gnome problem, because this desktop environment does not support tray icons. So either file a bug report to the Gnome developers or to the developer whose shell extension is used to display trayicons.

**Comment by mmahmoudian** [comment]
@kpcee I don't think this has anything to do with tray icon. the OP said that the `flameshot gui` doesn't do anything where in fact it should, plus @zacharytyhacz said that he also has the same issue on i3 which is not on Wayland. I think this needs some invstigation. I myself havenät been able to reproduce this.

**Comment by n1ngu** [comment]
I have 2 Arch boxes. In one of them everything works fine, in the other one, the `flameshot gui` will shot a full desktop screenshot instead of opening the GUI. So this might be a misconfiguration issue?

**Comment by ambition-echo** [comment]
> I have 2 Arch boxes (Manjaro, actually). In one of them everything works fine, in the other one, the `flameshot gui` will shot a full desktop screenshot instead of opening the GUI. So this might be a misconfiguration issue?

I have the same problem as you, according to the error message, it should be a wayland problem, because it is normal when I use xorg, and this problem occurs after switching to wayland

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

**Comment by mmahmoudian** [comment]
@n1ngu
> I have 2 Arch boxes (Manjaro, actually). In one of them everything works fine, in the other one, the `flameshot gui` will shot a full desktop screenshot instead of opening the GUI. So this might be a misconfiguration issue?

let me guess: on one computer you have Gnome 41 Wayland and on the other one you have proper DE. Right? if so, your experience has nothing to do with this issue. If not, then please provide info of both your systems. My suggestion:

```sh
inxi --graphics --system
```

**Comment by zacharytyhacz** [comment]
I am planning on making a detailed issue about my specific issue - I do not use my Arch as much as I wish these days. Expect one soon - I will reference it here

**Comment by federicogibertoni** [comment]
@n1ngu can you post your configurations here so we can try to reproduce your situation to see if can solve the problem ?
My settings are default at the moment.

**Comment by n1ngu** [comment]
I didn't recall the wayland/x11 config but I totally did. I'll go to https://github.com/flameshot-org/flameshot/issues/2470 instead. Sorry for the noise and thanks for the tips.

**Comment by borgmanJeremy** [comment]
So is there any issue remaining here?

**Comment by federicogibertoni** [comment]
@borgmanJeremy The issue described at the beginning of the discussion is still happening on my machine.

**Comment by borgmanJeremy** [comment]
@federicogibertoni please install:
xdg-desktop-portal
xdg-desktop-portal-gnome

Then reboot and try again

**Comment by federicogibertoni** [comment]
@borgmanJeremy thanks for your suggestion.

I installed the packages that you said (also xdg-desktop-portal-gtk as dependency) and now when I type `flameshot gui` in the terminal it takes a screenshot of the full screen and opens it in the default Gnome's screenshot application. 
At this point, if I click on the "Cancel" button on the top left corner the terminal prints these 3 lines after the initial warning:

```
flameshot: error: Unable to capture screen
flameshot: error: Unable to capture screen
flameshot: info: Screenshot aborted.
```

and then closes the program.

But, if I click on the "Share" button it opens Flameshot as expected. showing the gui and letting me take screenshots.

Is there anything else I can do to solve this situation ? Looks like Gnome is intercepting the screen capture before Flameshot and opens a dialog from which I can choose to launch Flameshot (by the "Share" button).
Even uninstalling `gnome-screenshot` doesn't seem to solve the problem, it still opens the default Gnome screenshot application before Flameshot.

**Comment by federicogibertoni** [comment]
Searching on the web it looks like this problem has already been [discussed](https://www.reddit.com/r/gnome/comments/r7j3dp/new_gnome_version_damages_the_workflow_of/).
User [owflovd](https://www.reddit.com/user/owflovd/) said that the method used by flameshot allowed ACE and should not be used.
Also, this is also mentioned in the [xdg-desktop-portal issue page](https://github.com/flatpak/xdg-desktop-portal/issues/649).

I think this is a more deep problem that should be fixed in future releases, if it hasn't already been done.

**Comment by borgmanJeremy** [comment]
Okay so its working fine then. You probably want to ask the arch maintainers to add xdg-desktop-portal as a optional dependency. 

There is absolutely **nothing** than can be done about this from a Flameshot perspective. This was an intentional change by gnome.

**Comment by bendavis78** [comment]
I still have an issue on Wayland. When I run from the command line:

```
$ flameshot
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
```

I'm using  flameshot-12.1.0-3

**Comment by mmahmoudian** [comment]
@bendavis78 this issue is fixed, and I'm pretty sure Flameshot works on Arch and Arch derivatives in X11 and Wayland (Gnome, KDE, Sway, Hyprland). Please open a new issue/bug report and fill all required fields so that it can be worked on. Thanks.

**Comment by julio899** [comment]
I can resolve making an icon launch 
I'm using Manjaro 

OS: Manjaro Linux x86_64
Kernel: 6.6.26-1-MANJARO 

create in Desktop 
file > Flameshot.desktop

```
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=Flameshot
Exec=/usr/bin/flameshot gui
Icon=flameshot
StartupWMClass=crx_majiogicmcnmdhhlgmkahaleckhjbmlk
Comment=
Path=
StartupNotify=false
```
add execution
Change icon
and double click

I hope it can be of help to someone, this was my humble solution that I was able to implement
