### ISSUE TITLE
Changes in v13.1.0 Broke Screenshot on Linux

### ISSUE THREAD

**Issue by k4yt3x** [flameshot-org/flameshot#4171]
### Flameshot Version

13.1.0-1

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Arch Linux x86_64 6.16.1-arch1-1

### Description

After updating from Flameshot v13.0.1 to v13.1.0, the screen capture widget overlay (that allows you to preview and edit the screenshot) incorrectly scaled and smaller than it should be. This makes it harder to edit the image and the resulting image has aliasing artifacts.

### Steps to reproduce

1. Install Flameshot v13.1.0 on Linux (tested on i3wm with X11)
2. Take a screenshot in GUI mode
3. Observe that the screenshot preview/edit widget has the wrong scale
4. After copying/saving the screenshot, it's in the wrong size and aliased

### Screenshots or screen recordings

Here's a screenshot taken by v13.0.1, which functions correctly:

<img width="3439" height="1439" alt="Image" src="https://github.com/user-attachments/assets/70506cf2-a74a-447f-9c71-ac14454c24f8" />

Here's a screenshot by v13.1.0:

<img width="3439" height="1439" alt="Image" src="https://github.com/user-attachments/assets/a4d499f0-e616-434a-b882-2423c71e813f" />

You can observe that the screenshot edit/preview is at the wrong scale (smaller than it should be) so it's not overlaying the entire display and also causing aliasing artifacts over the text. 

### System Information

- OS: Arch Linux x86_64
- Kernel: Linux 6.16.1-arch1-1
- WM: i3 4.24 (X11)
- Display: 3440x1440 @ 160 Hz in 34" [External]

**Comment by rostislaved** [comment]
I can confirm this. 
13.0.1 is okay, but 13.1.0 has this behavior

OS: Arch Linux x86_64
Kernel: 6.16.0-arch2-1
WM: i3 4.24 (X11)
Display (DELL U4025QW): 5120x2160 @ 120 Hz in 40" [External]

**Comment by borgmanJeremy** [comment]
Thanks for reporting. This means the fractional scaling adjustments removed in #4127 need to be added back. Unfortunately they seem to break other window managers

**Comment by borgmanJeremy** [comment]
Could you please test the builds from this pr and report back?

https://github.com/flameshot-org/flameshot/pull/4169

**Comment by k4yt3x** [comment]
Sorry AUR is a little dead right now

<img width="1840" height="227" alt="Image" src="https://github.com/user-attachments/assets/31ca40c9-3088-41fe-ab9e-f66378f1d95e" />

<img width="957" height="185" alt="Image" src="https://github.com/user-attachments/assets/b989425b-b6d6-48d0-9a33-5e3f7b31a0bc" />

Can't clone the PKGBUILD. I'll try again tomorrow.

**Comment by vargn** [comment]
FWIW, I encounter a similar issue with my multi-monitor setup. It seems to be only taking a screenshot of the main monitor and moves it to the upper left corner of the virtual display.

Don't mind the proportions being off, but see monitor layout below.

```
            ┌───────────┐  
┌───────┐   │           │  
│       │   │           │  
│       ├───┴───────────┴──┐
│       │                  │
│       │      MAIN        │
│       │                  │
└───────┴──────────────────┘ 
```

**UPDATE:** Problem solved with v13.1.0. Realized I was still on v13.0.1 as the Manjaro repo had not yet updated to v13.1.0 which is the version of the Arch repo. Second time this happens, and I should really just bite the bullet and move to Arch. It's time lol

## System Information
OS: Manjaro
Kernel: 6.12.41-1-MANJARO
WM: i3 4.24 (X11)
Display: 
3440x1440 @ 144 Hz in 34"
2560x1440 @ 60 Hz in 27"
1440x2560 @ 60 Hz in 27"

**Comment by TCROC** [comment]
> FWIW, I encounter a similar issue with my multi-monitor setup. It seems to be only taking a screenshot of the main monitor and moves it to the upper left corner of the virtual display.
> 
> Don't mind the proportions being off, but see monitor layout below.
> 
> ```
>             ┌───────────┐  
> ┌───────┐   │           │  
> │       │   │           │  
> │       ├───┴───────────┴──┐
> │       │                  │
> │       │      MAIN        │
> │       │                  │
> └───────┴──────────────────┘ 
> ```
> 
> **UPDATE:** Problem solved with v13.1.0. Realized I was still on v13.0.1 as the Manjaro repo had not yet updated to v13.1.0 which is the version of the Arch repo. Second time this happens, and I should really just bite the bullet and move to Arch. It's time lol
> ## System Information
> 
> OS: Manjaro Kernel: 6.12.41-1-MANJARO WM: i3 4.24 (X11) Display: 3440x1440 @ 144 Hz in 34" 2560x1440 @ 60 Hz in 27" 1440x2560 @ 60 Hz in 27"

@vargn I am encountering this exact issue with flatpak version 13.1.0.  Here's the about:

```
Flameshot v13.1.0 (79395fd)
Compiled with Qt 6.9.0
linux: 6.12.10-76061203-generic
org.kde.Platform: 6.9
```

It may also be related to this issue: https://github.com/flameshot-org/flameshot/issues/4172

But your description is exactly what I'm experiencing on the latest version

**Comment by inverse** [comment]
Downgrading from 13.1.0 to 13.0.1 fixed the issue for me on x11

**Comment by Spoffy** [comment]
I started seeing something like this today after upgrading to v13.1 on Arch, when using i3 4.21-1 and X11. 

On a single monitor, `flameshot gui` would should a preview that took up approximately 4/5ths of the screen horizontally, and 2/3rds of the screen vertically.

When using two monitors, it was clear that flameshot wasn't filling the screen on the top monitor. 

I've attached images that demonstrate the issue. 

Reverting back to v12.1 is a temporary workaround for the issue - I've yet to test v13.0.

 (Apologies for the poor photo quality - it seemed easier to do this than try to grab a screenshot of flameshot across two monitors).

![Image](https://github.com/user-attachments/assets/5e050784-35c6-4a38-a48f-a1a7338cd406)
![Image](https://github.com/user-attachments/assets/09967d2e-0dd9-4737-85cc-32910b1eb33a)

**Comment by GenesisOfTime** [comment]
I have the same problem  as Spoffy. I'm on a single-monitor setup.

What happened? I had to downgrade flameshot.

**Comment by webcheating** [comment]
hi, I had the same issue on my laptop (AMD iGPU, running X11 + Openbox).
Flameshot GUI was broken with white borders / screen shrinking, and it looked exactly like yours

**What fixed it for me was disabling Qt’s automatic HiDPI scaling:**

```
QT_ENABLE_HIGHDPI_SCALING=0 flameshot gui
```

**After adding this environment variable, Flameshot works normally again.**
hope it helps


<img width="380" height="260" alt="Image" src="https://github.com/user-attachments/assets/ed177d41-e97b-45ad-87f6-fee80e4085c2" />

<img width="380" height="260" alt="Image" src="https://github.com/user-attachments/assets/67d61f4d-b99f-4437-a0f0-359b618bfa50" />

**Comment by TCROC** [comment]
That didn't fix it for me.  But I did run from the command line and get some additional logs:

```
tcroc@pop-os:~/dev/BlockyBallOT$ flatpak run org.flameshot.Flameshot gui
Unable to get current screen, starting to use primary screen. It may be a cause of logical error and working with a wrong screen.
QLayout: Attempting to add QLayout "" to SidePanelWidget "", which already has a layout
Unable to get current screen, starting to use primary screen. It may be a cause of logical error and working with a wrong screen.
Unable to get current screen, starting to use primary screen. It may be a cause of logical error and working with a wrong screen.
Unable to get current screen, starting to use primary screen. It may be a cause of logical error and working with a wrong screen.
flameshot: info: Screenshot aborted.
QThreadStorage: entry 2 destroyed before end of thread 0x63460ab816a0
QThreadStorage: entry 1 destroyed before end of thread 0x63460ab816a0
```

NOTE:

I'm using wayland on pop os

**Comment by k4yt3x** [comment]
@borgmanJeremy Sorry I'm a bit hammered at work. Doesn't look like I'll have time to help test the patches here. Would be great if someone else here could help out.

**Comment by webcheating** [comment]
> Could you please test the builds from this pr and report back?
> 
> [#4169](https://github.com/flameshot-org/flameshot/pull/4169)

Tested the build on arch linux. 
kernel: 6.16.1-arch1-1
wm: openbox (X11)

The screen capture widget overlay no longer shrinks and the white bars are gone. However, the screenshot quality appears significantly lower than before.

Here is an example of screenshot from [#4169](https://github.com/flameshot-org/flameshot/pull/4169):

<img width="1602" height="901" alt="Image" src="https://github.com/user-attachments/assets/bab96dc5-9920-43f9-8bb6-2bd3fb3d63c6" />

And here is a screenshot from the old working version of Flameshot, or with the environment variable ```QT_ENABLE_HIGHDPI_SCALING=0``` (at least it works for me):

<img width="1919" height="1079" alt="Image" src="https://github.com/user-attachments/assets/a2ccb5c5-c31a-44b4-a6f1-e522d20fe8f0" />

Sorry in advance, I might have done something wrong, but for me it doesn’t seem to work correctly

**Comment by TCROC** [comment]
https://github.com/flameshot-org/flameshot/issues/4171#issuecomment-3207454419

^ I see my comment got marked as off topic.  Is my issue separate?  Should I open up a different issue?  This description sounded extremely similar to what I was experiencing

**Comment by borgmanJeremy** [comment]
@TCROC apologies i likely meant to hide it as a duplicate. I'm trying keep the "me too" posts hidden so in my limited time to work on this I can quickly scan the issue to remember what's going on. That's really hard to do when there's 90+ duplicate comments on some issues and I'm probably leaning to far in the "just hide" direction

**Comment by TCROC** [comment]
> [@TCROC](https://github.com/TCROC) apologies i likely meant to hide it as a duplicate. I'm trying keep the "me too" posts hidden so in my limited time to work on this I can quickly scan the issue to remember what's going on. That's really hard to do when there's 90+ duplicate comments on some issues and I'm probably leaning to far in the "just hide" direction

Absolutely know worries.  Feel free to hide this exchange as well to declutter the noise.  Was just posting those flatpak logs in the hope they help, but if its already posted, absolutely feel free to hide :).  Just wanted to make sure I was posting in the correct place.

ALSO

Absolutely LOVE flameshot!  I know as a maintainer, you normally hear about issues and don't get enough love.  This tool is a core component of my daily workflow! :)

**Comment by TCROC** [comment]
@mmahmoudian This is the issue I meant to post under.  Anyways, I found that the ``AppImage`` distributed on the releases page works just fine while the flatpak version does not.  ``AppImage`` about:

App Image
```
Flameshot v13.1.0 (79395fd)
Compiled with Qt 6.2.4
linux: 6.12.10-76061203-generic
pop: 22.04
```

Flatpak
```
Flameshot v13.1.0 (79395fd)
Compiled with Qt 6.9.0
linux: 6.12.10-76061203-generic
org.kde.Platform: 6.9
```

So the differences appear to be:

1. QT Version
1. Runtime? (pop vs org.kde.platform). Idk what category that really is.

Note: I'm running on XWayland (Wayland with X11 support)

**Comment by immanuelfodor** [comment]
I tried a workaround with `QT_ENABLE_HIGHDPI_SCALING=0 flameshot gui`, but it didn't resolve the issue. 

The screens shift to the left by half a monitor in my case:

<img width="1920" height="894" alt="Image" src="https://github.com/user-attachments/assets/44661d61-5d7b-4635-ba0c-d2d78aaf8c2d" />

<img width="1920" height="867" alt="Image" src="https://github.com/user-attachments/assets/cc700979-e2a3-43b3-8a7e-de15b8f1bd8b" />


```shell
❯ flameshot -v
Flameshot v13.0.1 ()
Compiled with Qt 6.9.1

❯ qtdiag 
Qt 5.15.17 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 15.1.1 20250425) on "xcb" 
OS: Manjaro Linux [linux version 6.16.0-5-MANJARO]
```

2-monitor setup, no scaling applied (100%):

<img width="604" height="240" alt="Image" src="https://github.com/user-attachments/assets/bc23a03c-5e5a-4f5d-b928-67d9535d18c2" />

**Comment by axolx** [comment]
In my case (Xorg 21.1.18, flameshot v13.1.0) the culprit was having `QT_SCALE_FACTOR > 1`.   Setting it to 1 worked around the issue.

**Comment by immanuelfodor** [comment]
My issue above (https://github.com/flameshot-org/flameshot/issues/4171#issuecomment-3224373685) has been fixed by flameshot-13.1.0-1 on Manjaro 🎉

**Comment by prezdev88** [comment]
# Fix Flameshot on Arch Linux with i3 (September 1st,  2025)

## Create a script that disables high DPI scaling:

Run this:

```bash
sudo bash -c 'cat > /usr/local/bin/flameshot-fixed << "EOF"
#!/bin/bash
QT_ENABLE_HIGHDPI_SCALING=0 flameshot gui
EOF
chmod +x /usr/local/bin/flameshot-fixed'
``` 

## Run flameshot like this

```bash
flameshot-fixed
```

**Comment by angrybacon** [comment]
I can reproduce with a single monitor, under X, no desktop environment, bare Qtile + Picom on Arch

```console
$ flameshot -v
Flameshot v13.1.0 ()
Compiled with Qt 6.9.1
```

And `QT_ENABLE_HIGHDPI_SCALING=0 flameshot gui` isn't convenient but makes it run fine

**Comment by TCROC** [comment]
> I can reproduce with a single monitor, under X, no desktop environment, bare Qtile + Picom on Arch
> 
> $ flameshot -v
> Flameshot v13.1.0 ()
> Compiled with Qt 6.9.1
> 
> And `QT_ENABLE_HIGHDPI_SCALING=0 flameshot gui` isn't convenient but makes it run fine

Just got around to testing.  Unfortunately, this does not fix it for the flatpak build :/

**Comment by TCROC** [comment]
I did get some new logs when reinstalling it tho:

```
tcroc@pop-os:~/dev/BlockyBallOT$ flatpak run org.flameshot.Flameshot
Unable to get current screen, starting to use primary screen. It may be a cause of logical error and working with a wrong screen.
QLayout: Attempting to add QLayout "" to SidePanelWidget "", which already has a layout
Unable to get current screen, starting to use primary screen. It may be a cause of logical error and working with a wrong screen.
Unable to get current screen, starting to use primary screen. It may be a cause of logical error and working with a wrong screen.
Unable to get current screen, starting to use primary screen. It may be a cause of logical error and working with a wrong screen.
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setCompositionMode: Painter not active
QPainter::translate: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::drawEllipse: Painter not active
QPainter::setBrush: Painter not active
QPainter::drawEllipse: Painter not active
```

**Comment by almirb** [comment]
I'm using Win 11 and needed to go back to v12.1.0 to make It work well again.

**Comment by sinusx1986** [comment]
On Windows 11 I can confirm it too. Go back to 12.1.0

**Comment by erik55** [comment]
#4172 and #4171 and #4169 seem to be all duplicates, no?

**Comment by mmahmoudian** [comment]
Can folks who were experiencing this issue test the last commit in HEAD and let us know if it has solved the issue for them, since #4169 was merged which was attempting to fix this

@erik55 thanks for pointing this out.

**Comment by kaviev** [comment]
On Windows 10 I can confirm it too.

**Comment by vokamut** [comment]
Only reverting to version 12 in openSuse TW solved the problem:

```bash
sudo zypper in --oldpackage flameshot=12.1.0-3.5
```

**Comment by Saibamen** [comment]
Please retest with [v13.2.0](https://github.com/flameshot-org/flameshot/releases/tag/v13.2.0)

**Comment by mufasa71** [comment]
Fixed for me with latest version on Archlinux + X11 + i3

**Comment by bo0tzz** [comment]
Seems fixed for me too, on the same setup

**Comment by kaviev** [comment]
[v13.2.0](https://github.com/flameshot-org/flameshot/releases/tag/v13.2.0) fixed problem in Windows 10. Thanks!

**Comment by almirb** [comment]
I have bad news...   the screenshot area on a dual monitor setup on Windows 11 24H2 (26100.6899) is weird... tested with version 13.2.0.  I had to go back to v12.1.0.  

<img width="1280" height="638" alt="Image" src="https://github.com/user-attachments/assets/ef53c38f-1c4d-4cc9-95e5-517961cc5273" />

PS.: I can support the devs with testing on my environment.

**Comment by igor-hara** [comment]
Yea, same here, like this bus is still present for a month now.

**Comment by mmahmoudian** [comment]
This should have been fixed with #4498 
If you can, try compiling from the master branch and let us know is this issue still persists. I'm going to close this for now, but if the issue persists, we will re-open it.

**Comment by erik55** [comment]
For all X11 users (I use Xmonad): You can use this pull request https://github.com/flameshot-org/flameshot/pull/4535 to get the old behaviour of version 12 back, but with QT6 instead of QT5. No workarounds needed.

**Comment by k4yt3x** [comment]
@mmahmoudian I've been using flameshot with `QT_ENABLE_HIGHDPI_SCALING=0` without issues. However, if I launch flameshot without this envar, I get a white border along the bottom and right side of the screen. Also it seems like the image is a pixel or two off towards the top left:

<img width="1688" height="733" alt="Image" src="https://github.com/user-attachments/assets/19c7d00c-bcf9-47d2-81bb-0280222ebd53" />
